Working out details mentioned in: https://aosabook.org/en/500L/a-python-interpreter-written-in-python.html

To get immediate feedback, let's build a small interpreter that adds together numbers. Like `7 + 5` and so on.

The interpreter we are going to build is a Stack based interpreter. Meaning we manipulate the stack to execute instructions of our program.

Let's take a look at the instructions we need to add numbers.
1. `LOAD_VALUE`
2. `ADD_TWO_VALUES`
3. `PRINT_ANSWER`

Let's say we are trying to `7 + 5`. We represent this code in instructions like:
```python
what_to_execute = {
    "instructions": [("LOAD_VALUE", 0),
                     ("LOAD_VALUE", 1),
                     ("ADD_TWO_VALUES", None),
                     ("PRINT_ANSWER", None)
                    ],
    "numbers": [7, 5]
}
```

So in the stack machine, the state would look something like:
1. Empty stack. `[]`
2. `LOAD_VALUE 7`, `[7]`
3. `LOAD_VALUE 5`, `[7, 5]`
4. `ADD_TWO_VALUES`, `[12]` => `7 + 5` = 12
5. `PRINT_ANSWER`, `[]` => pop the result from the stack


Let's build an interpreter for this.

In [3]:
# An Interpreter to add numbers

class Interpreter:
    def __init__(self):
        self.stack = []

    def LOAD_VALUE(self, number: int):
        self.stack.append(number)

    def PRINT_ANSWER(self):
        result = self.stack.pop()
        print(result)

    def ADD_TWO_VALUES(self):
        first_num = self.stack.pop()
        second_num = self.stack.pop()
        total = first_num + second_num
        self.stack.append(total)

    def run_code(self, what_to_execute: object):
        instructions = what_to_execute["instructions"]
        numbers = what_to_execute["numbers"]

        for each_step in instructions:
            instruction, argument = each_step
            if instruction == "LOAD_VALUE":
                self.LOAD_VALUE(numbers[argument])
            elif instruction == "ADD_TWO_VALUES":
                self.ADD_TWO_VALUES()
            elif instruction == "PRINT_ANSWER":
                self.PRINT_ANSWER()

what_to_execute = {
    "instructions": [("LOAD_VALUE", 0), ("LOAD_VALUE", 1), ("ADD_TWO_VALUES", None), ("PRINT_ANSWER", None)],
    "numbers": [7, 5]
}

interpreter = Interpreter()
interpreter.run_code(what_to_execute) # should print 12

12


Using the same interpreter what if we want to add *n* numbers? We can modify the instructions such that it can add numbers. Let's look at that.

In [4]:
what_to_execute = {
    "instructions": [
        ("LOAD_VALUE", 0), ("LOAD_VALUE", 1), ("ADD_TWO_VALUES", None), ("LOAD_VALUE", 2), ("LOAD_VALUE", 3),
        ("ADD_TWO_VALUES", None), ("ADD_TWO_VALUES", None), ("PRINT_ANSWER", None)
    ],
    "numbers": [100, 200, 1500, 40]
}

interpreter = Interpreter()
interpreter.run_code(what_to_execute) # should print 1840

1840


### Variables

Next lets add Variables to our interpreter. Variables require an instruction for storing the value of a variable, `STORE_NAME`; an instruction for retrieving it `LOAD_NAME`; and a mapping from variable names to values.

For now, we'll ignore the namespaces and scoping, so that we can store the variable mapping on the interpreter object itself.

Finally we have to make sure that `what_to_execute` has a list of variable names, in addition to its list of constants.

### Example
```python
def s():
    a = 1
    b = 2
    print(a + b)

# s is transformed into:

what_to_execute = {
    "instructions": [
        ("LOAD_VALUE", 0),
        ("STORE_NAME", 0),
        ("LOAD_VALUE", 1),
        ("STORE_NAME", 1),
        ("LOAD_NAME", 0),
        ("LOAD_NAME", 1),
        ("ADD_TWO_VALUES", None),
        ("PRINT_ANSWER", None)
    ],
    "numbers": [1, 2],
    "names": ["a", "b"]
}
```

To keep track of what names are bound to what values, we'll add an `environment` dictionary to the `__init__` method. We'll also add `STORE_NAME` and `LOAD_NAME`. These methods first look up variables in question and then use the dictionary to store or retrieve its value.

**NOTE:** The arguments of the instructions can now mean two different things. They can either be an index into the "numbers" list, or they can be an index into the "names" list. The interpreter knows which it should be by checking what instruction it's executing. We'll break out this logic -- and the mapping of instruction to what their arguments mean -- into a separate method.

In [5]:
# Updated code for Interpreter with support for Variable instructions
class Interpreter:
    def __init__(self):
        self.stack = []
        self.environment = {}

    def LOAD_VALUE(self, number: int):
        self.stack.append(number)

    def PRINT_ANSWER(self):
        result = self.stack.pop()
        print(result)

    def ADD_TWO_VALUES(self):
        first_num = self.stack.pop()
        second_num = self.stack.pop()
        total = first_num + second_num
        self.stack.append(total)

    def STORE_NAME(self, name):
        val = self.stack.pop()
        self.environment[name] = val

    def LOAD_NAME(self, name):
        val = self.environment[name]
        self.stack.append(val)

    def parse_argument(self, instruction, argument, what_to_execute):
        # Understand what the argument to each instruction means
        numbers = ["LOAD_VALUE"]
        names = ["LOAD_NAME", "STORE_NAME"]

        if instruction in numbers:
            argument = what_to_execute["numbers"][argument]
        elif instruction in names:
            argument = what_to_execute["names"][argument]
        
        return argument

    def run_code(self, what_to_execute):
        instructions = what_to_execute["instructions"]
        for each_step in instructions:
            instruction, argument = each_step
            argument = self.parse_argument(instruction, argument, what_to_execute)

            if instruction == "LOAD_VALUE":
                self.LOAD_VALUE(argument)
            elif instruction == "LOAD_NAME":
                self.LOAD_NAME(argument)
            elif instruction == "STORE_NAME":
                self.STORE_NAME(argument)
            elif instruction == "ADD_TWO_VALUES":
                self.ADD_TWO_VALUES()
            elif instruction == "PRINT_ANSWER":
                self.PRINT_ANSWER()

    def execute_code(self, what_to_execute):
        instructions = what_to_execute["instructions"]
        for each_step in instructions:
            instruction, argument = each_step
            argument = self.parse_argument(instruction, argument, what_to_execute)
            bytecode_method = getattr(self, instruction)
            if argument is None:
                bytecode_method()
            else:
                bytecode_method(argument)


what_to_execute = {
    "instructions": [
        ("LOAD_VALUE", 0),
        ("STORE_NAME", 0),
        ("LOAD_VALUE", 1),
        ("STORE_NAME", 1),
        ("LOAD_NAME", 0),
        ("LOAD_NAME", 1),
        ("ADD_TWO_VALUES", None),
        ("PRINT_ANSWER", None)
    ],
    "numbers": [1, 2],
    "names": ["a", "b"]
}

interpreter = Interpreter()
interpreter.run_code(what_to_execute)
# interpreter.execute_code(what_to_execute)


3


Even with just five instructions, the `run_code` method is starting to get tedious. If we have to add one more instruction, then we have to add an if branch and that makes our code bloated. To fix this, we can use Python's dynamic method lookup. We can use the `getattr` function to look up the method on the fly. Let's implement it in the above cell. Check out the `execute_code` method.

### Real Python Bytecode
At time point, we'll abandon our toy instruction sets and switch to real Python bytecode. The structure of the bytecode is similar to our toy interpreter's instruction sets, except it uses one byte instead of a long name to identify each instruction.

We'll walkthrough the bytecode of a small function
```python
def cond():
    x = 3
    if x < 5:
        return 'yes'
    else:
        return 'no'
```

In [6]:
# __code__ and .co_code methods

def cond():
    x = 3
    if x < 5:
        return 'yes'
    else:
        return 'no'

print(cond.__code__.co_code)

# cond.__code__ returns a code object
# cond.__code__.co_code returns the bytecode as raw bytes

b'd\x01}\x00|\x00d\x02k\x00r\x08d\x03S\x00d\x04S\x00'


By looking at the raw bytes of the bytecode, its hard to infer things. Let's turn that into a list of integers. We can do that by `list(cond.__code__.co_code)`

In [7]:
print(list(cond.__code__.co_code)) # the bytecode as numbers. These are series of bytes

[100, 1, 125, 0, 124, 0, 100, 2, 107, 0, 114, 8, 100, 3, 83, 0, 100, 4, 83, 0]


Let's take a look at a powerful tool which helps us look into this data clearly. That is the Python `dis` module, short for **bytecode disassembler**. A disassembler takes low-level code that is written for machines, like assembly code or bytecode, and prints it in a human-readable way.

When we run `dis.dis`, it outputs an explanation of the bytecode it has passed.

In [8]:
# Run this cell to see the bytecode of the `cond` function
import dis

dis.dis(cond)

  4           0 LOAD_CONST               1 (3)
              2 STORE_FAST               0 (x)

  5           4 LOAD_FAST                0 (x)
              6 LOAD_CONST               2 (5)
              8 COMPARE_OP               0 (<)
             10 POP_JUMP_IF_FALSE        8 (to 16)

  6          12 LOAD_CONST               3 ('yes')
             14 RETURN_VALUE

  8     >>   16 LOAD_CONST               4 ('no')
             18 RETURN_VALUE


### Lets go through the bytecode step by step

Let's take the first instruction `LOAD_CONST` as an example.

* The number in the first column (4) shows the line number in our python source code.
* The second column is an index into the bytecode, telling us that `LOAD_CONST` instruction appears at position zero
* The third column is the instruction itself, mapped to its human-readable name.
* The forth column, when present, is the argument to that instruction.
* The fifth column, when present, is a hint about what the argument means

### Raw Bytes
Looking at the first few bytes of this bytecode: [100, 1, 125, 0, 124, 0]

These 6 bytes represents the first 3 instructions with their arguments. We can use `dis.opname`, a mapping from bytes to intelligible strings, to find what instructions 100, 125 and 124 map to:

In [9]:
print(dis.opname[100])
print(dis.opname[125])
print(dis.opname[124])

LOAD_CONST
STORE_FAST
LOAD_FAST


### Conditionals and Loops
So far, the interpreter has executed code simply by stepping through the instructions one by one. This is a problem; often we want to execute certain instructions multiple times, or skip them under certain conditions. To allow us to write loops and conditionals, the interpreter must be able to jump around in the instruction set. In a sense, Python handles loops and conditionals using `GOTO` statements in bytecode! Look at the disassembly of the bytecode again!

In [10]:
dis.dis(cond)

  4           0 LOAD_CONST               1 (3)
              2 STORE_FAST               0 (x)

  5           4 LOAD_FAST                0 (x)
              6 LOAD_CONST               2 (5)
              8 COMPARE_OP               0 (<)
             10 POP_JUMP_IF_FALSE        8 (to 16)

  6          12 LOAD_CONST               3 ('yes')
             14 RETURN_VALUE

  8     >>   16 LOAD_CONST               4 ('no')
             18 RETURN_VALUE


The conditional `x < 5` on line 5 of the code is compiled into four instructions: `LOAD_FAST`, `LOAD_CONST`, `COMPARE_OP`, `POP_JUMP_IF_FALSE`.

`x < 5` generates code to load `x`, load `5`, and compares the two values. The instruction `POP_JUMP_IF_FALSE` is responsible for implementing the `if`. This instruction will pop the top value off the interpreter's stack. If the value is true, then nothing happens. (The value can be "truthy" -- it doesn't have to be the literal `True` object). If the value is `false`, then the interpreter will jump to another instruction.

The instruction to land on is called the jump target, and its provided as the argument to the `POP_JUMP` instruction. Here, the jump target is `16`. The instruction at `16` is `LOAD_CONST` on line `8`. (`dis` marks the jump targets with `>>`).

If the result of `x < 5` is False, then the interpreter will jump straight to line 8 (`return "no"`), skipping line 4 (`return "yes"`). Thus, the interpreter uses jump instruction to selectively skip over the parts of the instruction set.

Let's look at an example for loops.

In [11]:
def loop():
    x = 1
    while x < 5:
        x = x + 1
    return x

import dis
dis.dis(loop)

  2           0 LOAD_CONST               1 (1)
              2 STORE_FAST               0 (x)

  3           4 LOAD_FAST                0 (x)
              6 LOAD_CONST               2 (5)
              8 COMPARE_OP               0 (<)
             10 POP_JUMP_IF_FALSE       14 (to 28)

  4     >>   12 LOAD_FAST                0 (x)
             14 LOAD_CONST               1 (1)
             16 BINARY_ADD
             18 STORE_FAST               0 (x)

  3          20 LOAD_FAST                0 (x)
             22 LOAD_CONST               2 (5)
             24 COMPARE_OP               0 (<)
             26 POP_JUMP_IF_TRUE         6 (to 12)

  5     >>   28 LOAD_FAST                0 (x)
             30 RETURN_VALUE


Python loops also rely on jumping. In the bytecode above, notice that the line `while x < 5` generates almost identitical bytecode to `if x < 10`. In both the cases, the comparison is calculated and then `POP_JUMP_IF_FALSE` controls which instruction is executed next.

### Exploring Bytecode

* What is the difference between a for loop and while loop to the Python interpreter? Let's see.

In [12]:
# For loop example
def for_loop():
    x = 1
    for i in range(5):
        x = x + i
    return x

import dis
dis.dis(for_loop)

  3           0 LOAD_CONST               1 (1)
              2 STORE_FAST               0 (x)

  4           4 LOAD_GLOBAL              0 (range)
              6 LOAD_CONST               2 (5)
              8 CALL_FUNCTION            1
             10 GET_ITER
        >>   12 FOR_ITER                 6 (to 26)
             14 STORE_FAST               1 (i)

  5          16 LOAD_FAST                0 (x)
             18 LOAD_FAST                1 (i)
             20 BINARY_ADD
             22 STORE_FAST               0 (x)
             24 JUMP_ABSOLUTE            6 (to 12)

  6     >>   26 LOAD_FAST                0 (x)
             28 RETURN_VALUE


* We are loading 1 to `x`
* We are loading the global function `range`
* We are loading the constant `5`
* Once we loaded `5`, we are calling the range function using `CALL_FUNCTION` instruction. This function returns an iterable and puts it on the stack
* Next we execute `FOR_ITER` instruction. This does two things
    * It calls the `__next__()` method in the iterator which is present in the stack
    * If `__next__` yields a new value, push it on the stack (leaving the iterator below it).
    * If the iterator indicates it is exhausted then the byte code counter is incremented by delta (here delta is 26)
* Once the iterator is exhausted, it executes the instruction at index `26`, which is `LOAD_FAST`. This loads the value which presents on top of the stack into `x`
* Finally, `RETURN_VALUE` instruction is executed. Which returns the value of `x`

## Frames
So far, we've learned that the Python virtual machine is a stack machine. It steps and jumps through instructions, pushing and popping values on and off a stack. There are still some gaps in our mental model though. In the example above, the last instruction is `RETURN_VALUE` which corresponds to the `return` statement in the code. But where does the instruction return to?

To answer this question. we must add a layer of complexity: **the frame**. A frame is a collection of information and context for a chuck of code. Frames are created and destroyed on the fly as your Python code executes. There's one frame corresponding to each *call* of a function - so each frame has one code object associated with it, a code object can have many frames. If you had a function that called itself recursively ten times, you'd have eleven frames - one for each level of recursion and one for the module you started from. In general, there's a frame for each scope in a Python program. For example, each module, each function call, and each class definition has a frame.

Frames live on a *call stack*, a completely different stack from the ones we've been discussing so far. (The call stack is the stack you're most familiar with already) - you've seen it printed out in the tracebacks of exceptions. Each line in the traceback starting with "File 'program.py', line 10" corresponds to one frame on the call stack.). The stack we've been examining - the one the interpreter is manipulating while it executes bytecode - we'll call the *data stack*. There's also a third stack, called the *block stack*. Blocks are used for certain kind of control flow, particularly looping and exception handling. Each frame on the call stack has its own data stack and block stack.

Types of stacks we've discussed so far:
* Call stack
* Data stack
* Block stack

Lets make this concrete with an example. Suppose the Python interpreter is currently executing the line marked 3 below. The interpreter is in the middle of a call to `foo`, which is in turn calling `bar`. The diagram shows a schematic of a call stack of frames, the block stacs, and the data stacks. 

```python
def bar(y):
    z = y + 3       # <--- (3) ... and the interpreter is here
    return z

def foo():
    a = 1
    b = 2
    return a + bar(b)   # <--- (2) ... which is returning a call to bar ...

foo()       # <--- (1) We're in the middle of a call to foo...
```

![Call stack](./assets/call_stack.png)